apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  annotations:
    # Paksa Argo CD untuk tidak pull ulang dari registry
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: my-python-app:latest
        # Tambahkan ini untuk memastikan image diambil dari local registry
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
spec:
  selector:
    app: my-python-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
